In [1]:
import numpy as np 
import pandas as pd 
import sklearn

In [28]:
df = pd.read_csv("\\Users\\mpstme.student\\Downloads\\LDA.csv")

FileNotFoundError: [Errno 2] No such file or directory: '\\Users\\mpstme.student\\Downloads\\LDA.csv'

In [29]:
df

,Account,X,Y,Unnamed: 3,Z score,Unnamed: 5,Unnamed: 6,Y.1,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,1,1.1,13,1,4.881240,1,NaN,9.000000,NaN,Mean,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1.5,15,1,6.190730,1,NaN,3.328063,NaN,G1,...,M1-M2,0.4,NaN,sw,0.171579,-0.089474,NaN,sw-1,5.835697,0.014336
2,3,1.2,17,1,5.806012,1,NaN,7.582016,NaN,G2,...,NaN,6.0,NaN,NaN,-0.089474,36.421053,NaN,NaN,0.014336,0.027492
3,4,0.9,21,1,5.762666,1,NaN,11.835968,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1.6,7,1,5.067274,1,NaN,1.910079,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,2.2,8,1,6.690137,1,NaN,-6.597826,Overall X,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,2.420296,NaN
6,7,0.9,16,1,4.909238,1,NaN,11.835968,Overall Y,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.170686,NaN
7,8,1.0,13,1,4.639210,1,NaN,10.417984,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,1.3,8,1,4.511871,1,NaN,6.164032,NaN,4.198497135,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,1.3,2,1,3.487756,2,NaN,6.164032,NaN,x = my+c,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,0.7,11,2,3.571750,2,NaN,14.671937,intercept,1.734703833,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,0.9,-4,2,1.495524,2,NaN,11.835968,slope,-0.070522648,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,0.8,6,2,2.960351,2,NaN,13.253953,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,1.3,2,2,3.487756,2,NaN,6.164032,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,1.1,6,2,3.686440,2,NaN,9.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,0.5,8,2,2.575634,2,NaN,17.507905,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,0.3,8,2,2.091574,2,NaN,20.343874,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,1.4,6,2,4.412529,1,NaN,4.746047,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,0.9,3,2,2.690324,2,NaN,11.835968,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,1.1,14,2,5.051926,1,NaN,9.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as lda

In [13]:
x= df.iloc[:,0:2]
x.shape
#t = df['X','Y']
#t.shape
y = df.iloc[:,2:3]
y.shape
#t1 = df['Group']
#t1.shape

(20, 1)

In [21]:
LDA=lda(n_components=1)
LDA.fit(x,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

LinearDiscriminantAnalysis(n_components=1)

In [22]:
X_lda = LDA.transform(x)

In [23]:
X_lda

array([[ 3.05990345],
       [ 2.09215898],
       [ 2.25430091],
       [ 2.41644283],
       [ 0.96446134],
       [-0.32610782],
       [ 1.45015753],
       [ 0.96665009],
       [ 0.16031796],
       [-0.16177714],
       [ 0.48460182],
       [-0.16031796],
       [-0.32100072],
       [-1.45015753],
       [-1.44942795],
       [-0.80304899],
       [-0.80231941],
       [-2.89995028],
       [-2.41498366],
       [-3.05990345]])

In [30]:
LDA.predict(x)

array([13, 13, 13, 13,  8,  8, 13,  8,  8,  8,  8,  8,  8,  6,  6,  8,  8,
        6,  6, 14], dtype=int64)